server:
  port: 9090
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/studenttopdf?serverTimezone=Asia/Shanghai
      username: root
      password: 1234

